# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {Y:/Google Drive/SLU/_CMPS 375/_units/03_ vivado 4bit adder/DispAdder4/DispAdder4.cache/wt} [current_project]
set_property parent.project_path {Y:/Google Drive/SLU/_CMPS 375/_units/03_ vivado 4bit adder/DispAdder4/DispAdder4.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo {y:/Google Drive/SLU/_CMPS 375/_units/03_ vivado 4bit adder/DispAdder4/DispAdder4.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  {Y:/Google Drive/SLU/_CMPS 375/_units/03_ vivado 4bit adder/DispAdder4/DispAdder4.srcs/sources_1/imports/__adder1 source files__/Adder1.vhd}
  {Y:/Google Drive/SLU/_CMPS 375/_units/03_ vivado 4bit adder/DispAdder4/DispAdder4.srcs/sources_1/imports/new/Bin2Hex.vhd}
  {Y:/Google Drive/SLU/_CMPS 375/_units/03_ vivado 4bit adder/DispAdder4/DispAdder4.srcs/sources_1/imports/new/Adder4.vhd}
  {Y:/Google Drive/SLU/_CMPS 375/_units/03_ vivado 4bit adder/DispAdder4/DispAdder4.srcs/sources_1/imports/new/DispAdder4.vhd}
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{Y:/Google Drive/SLU/_CMPS 375/_units/03_ vivado 4bit adder/DispAdder4/DispAdder4.srcs/constrs_1/imports/__adder1 source files__/DispAdder4.xdc}}
set_property used_in_implementation false [get_files {{Y:/Google Drive/SLU/_CMPS 375/_units/03_ vivado 4bit adder/DispAdder4/DispAdder4.srcs/constrs_1/imports/__adder1 source files__/DispAdder4.xdc}}]


synth_design -top DispAdder4 -part xc7a100tcsg324-1


write_checkpoint -force -noxdef DispAdder4.dcp

catch { report_utilization -file DispAdder4_utilization_synth.rpt -pb DispAdder4_utilization_synth.pb }
